### ISSUE TITLE
Need a Lunch Menu!

### ISSUE THREAD

**Issue by blackhawk118** [IntroToCode/RecipesCodemates5#2]
## 💬 Discussion topic

We need to create a lunch menu.

## ❗ Potential issues

We need to pick with recipe to put into the lunch menu.

## 👥 People to consult

@jhpark89 @ojinchunk @m-mamer @blackhawk118 

## 📃 Details

We need to create a lunch menu with a recipe item. Each person needs to enter a recipe item.

**Comment by m-mamer** [comment]
Lunch menu is ready!
