### ISSUE TITLE
Need a Dinner menu!

### ISSUE THREAD

**Issue by blackhawk118** [IntroToCode/RecipesCodemates5#4]
## 💬 Discussion topic

We need a dinner menu.

## ❗ Potential issues

We need to pick which recipe will be on the menu.

## 👥 People to consult

@jhpark89 @ojinchunk @m-mamer @blackhawk118 

## 📃 Details

We need to create a dinner menu with a recipe item. Each person needs to enter a recipe item.

**Comment by m-mamer** [comment]
Dinner Menu is ready!
